cartesian_velocity_controller:
    type: panda_controllers/CartesianVelocityController
    arm_id: panda
    command_timeout: 3.0
    velocity_thresh:    # taken from documentation franka
        translation: 1.700
        rotation: 2.500
        elbow: 2.175
    low_pass_filter:
    - name: first_low_pass
      type: filters/TransferFunctionFilterDouble
      params:
        a: [1.0, -0.9971]
        b: [0.0014, 0.0014]
        
pd_controller:
    type: panda_controllers/PdController
    arm_id: panda
    joint_names:
         - panda_joint1
         - panda_joint2
         - panda_joint3
         - panda_joint4
         - panda_joint5
         - panda_joint6
         - panda_joint7
    kp1: 120.0
    kp2: 70.0
    kp3: 50.0
    kv: 10.0
    dt: 5

         
computed_torque_controller:
    type: panda_controllers/ComputedTorque
    arm_id: panda
    joint_names:
         - panda_joint1
         - panda_joint2
         - panda_joint3
         - panda_joint4
         - panda_joint5
         - panda_joint6
         - panda_joint7
    kp1: 120.0
    kp2: 70.0
    kp3: 50.0
    kv: 10.0
    dt: 5

back_stepping_controller:
    type: panda_controllers/BackStepping
    arm_id: panda
    joint_names:
         - panda_joint1
         - panda_joint2
         - panda_joint3
         - panda_joint4
         - panda_joint5
         - panda_joint6
         - panda_joint7
    kp1: 120.0
    kp2: 70.0
    kp3: 50.0
    kd: 10.0
    lambda: 1
    dt: 5

variable_impedance_controller:
    type: panda_controllers/VariableImpedanceController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    var_damp: true 

project_impedance_controller:
    type: panda_controllers/ProjectImpedanceController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    var_damp: true 

project_impedance_controller_quat:
    type: panda_controllers/ProjectImpedanceControllerQuat
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    var_damp: true 



# PROVA 2: K_default=200, SCENDE;PRENDE OGGETTO; RISALE; RISCENDE; LASCIA OGGETTO; RISALE
# traj_par: 
#     N_ACTION : 5
#     CUBE_RS : 2000.0
#     ACTIONS :
#         - [5.0, 0.4, 0.0, 0.3, 0.0]    # time, pos, gripper
#         - [15.0, 0.4, 0.0, 0.10, 3500.0]
#         - [10.0, 0.4,  0.0, 0.3, 400.0]
#         - [10.0, 0.4, 0.0, 0.10, 400.0]
#         - [10.0, 0.4, 0.0, 0.3, 3000.0]
#     TYPE :                          
#         - [0, 0, 0, 0, 0, 0]     # int, comp
#         - [0, 0, 1, 0, 0, 0]
#         - [0, 0, 0, 0, 0, 1]
#         - [0, 0, 1, 0, 0, 1]
#         - [0, 0, 1, 0, 0, 0]

#PROVA 3: K_z_default=100,SCENDE;PRENDE OGGETTO; RISALE; RISCENDE; PAUSA 2 sec; LASCIA OGGETTO; RISALE
# traj_par: 
#     N_ACTION : 6
#     CUBE_RS : 2000.0
#     ACTIONS :
#         - [5.0, 0.4, 0.0, 0.3, 0.0]    # time, pos, gripper
#         - [15.0, 0.4, 0.0, 0.10, 2500.0]
#         - [10.0, 0.4, 0.0, 0.3, 300.0]
#         - [5.0, 0.4, 0.0, 0.3, 300.0]   #pause
#         - [10.0, 0.4, 0.0, 0.10, 300.0]
#         - [10.0, 0.4, 0.0, 0.3, 2000.0]
#     TYPE :                          
#         - [0, 0, 0, 0, 0, 0]     # int, comp
#         - [0, 0, 1, 0, 0, 0]
#         - [0, 0, 1, 0, 0, 1]
#         - [0, 0, 0, 0, 0, 1]    #pause
#         - [0, 0, 1, 0, 0, 1]
#         - [0, 0, 1, 0, 0, 0]

# #PROVA 4: BOX, interaction with box without object
# traj_par: 
#     N_ACTION : 3
#     CUBE_RS : 2000.0
#     ACTIONS :
#         - [5.0, 0.4, 0.0, 0.4, 0.0]    # time, pos, gripper
#         - [8.0, 0.4, 0.0, 0.15, 0.0]
#         - [5.0, 0.4, 0.0, 0.4, 0.0]
#     TYPE :                          
#         - [0, 0, 0, 0, 0, 0]     # int, comp
#         - [0, 0, 1, 0, 0, 0]
#         - [0, 0, 1, 0, 0, 0]


# PROVE OGGI CHE SEMBRA 
# # PROVA 5: grasping object: scendo giù, prendo oggetto, salgo su; K = 100
# traj_par: 
#     N_ACTION : 3
#     CUBE_RS : 2000.0
#     ACTIONS :
#         - [5.0, 0.4, 0.0, 0.3, 0.0]    # time, pos, gripper
#         - [15.0, 0.4, 0.0, 0.07, 2500.0]
#         - [10.0, 0.4, 0.0, 0.3, 300.0]

#     TYPE :                          
#         - [0, 0, 0, 0, 0, 0]     # int, comp
#         - [0, 0, 1, 0, 0, 0]
#         - [0, 0, 1, 0, 0, 1]


# PROVA 6: K_x=K_y=500, K_z = 100, prendo peso piccolo, lo alzo, lo ripoggio, mi rialzo
# traj_par: 
#     N_ACTION : 6
#     CUBE_RS : 2000.0
#     ACTIONS :
#         - [5.0, 0.4, 0.0, 0.3, 0.0]    # time, pos, gripper
#         - [15.0, 0.4, 0.0, 0.10, 2500.0]
#         - [10.0, 0.4, 0.0, 0.3, 300.0]
#         - [5.0, 0.4, 0.0, 0.3, 300.0]   #pause
#         - [10.0, 0.4, 0.0, 0.10, 300.0]
#         - [10.0, 0.4, 0.0, 0.3, 2000.0]
#     TYPE :                          
#         - [0, 0, 0, 0, 0, 0]     # int, comp
#         - [0, 0, 1, 0, 0, 0]
#         - [0, 0, 1, 0, 0, 1] 
#         - [0, 0, 0, 0, 0, 1]    #pause
#         - [0, 0, 1, 0, 0, 1]
#         - [0, 0, 1, 0, 0, 0]

# PROVA 7: K_x e K_y = 200; k_z = 100, prendo peso grosso, salgo, scendo, lo poggio, risalgo
# traj_par: 
#     N_ACTION : 6
#     CUBE_RS : 2000.0
#     ACTIONS :
#         - [5.0, 0.4, 0.0, 0.3, 0.0]    # time, pos, gripper
#         - [15.0, 0.4, 0.0, 0.10, 3500.0]
#         - [10.0, 0.4, 0.0, 0.3, 400.0]
#         - [5.0, 0.4, 0.0, 0.3, 400.0]   #pause
#         - [10.0, 0.4, 0.0, 0.10, 400.0]
#         - [10.0, 0.4, 0.0, 0.3, 3000.0]
#     TYPE :                          
#         - [0, 0, 0, 0, 0, 0]     # int, comp
#         - [0, 0, 1, 0, 0, 0]
#         - [0, 0, 1, 0, 0, 1] 
#         - [0, 0, 0, 0, 0, 1]    #pause
#         - [0, 0, 1, 0, 0, 1]
#         - [0, 0, 1, 0, 0, 0]

# PROVA 8: INTERACTION WITH BOX: scende, prende oggetto leggero, sale, lo poggia sulla scatola e torna su 
# traj_par: 
#     N_ACTION : 7
#     CUBE_RS : 2000.0
#     ACTIONS :
#         - [5.0, 0.4, 0.0, 0.4, 0.0]    # time, pos, gripper
#         - [15.0, 0.4, 0.0, 0.10, 2500.0]
#         - [10.0, 0.4, 0.0, 0.4, 250.0]
#         - [5.0, 0.4, 0.0, 0.4, 250.0]   #pause
#         - [15.0, 0.65, 0.0, 0.4, 250]
#         - [10.0, 0.65, 0.0, 0.22, 250.0]
#         - [10.0, 0.65, 0.0, 0.4, 2500.0]
#     TYPE :                          
#         - [0, 0, 0, 0, 0, 0]     # int, comp
#         - [0, 0, 1, 0, 0, 0]
#         - [0, 0, 1, 0, 0, 1] 
#         - [0, 0, 0, 0, 0, 1]    #pause
#         - [0, 0, 0, 0, 0, 1]
#         - [0, 0, 1, 0, 0, 1]
#         - [0, 0, 1, 0, 0, 0]

# PROVA 9: traj più veloce, peso piccolo, scende,  prende oggetto leggero, sale, riscende, poggia oggetto e torna su 
# traj_par: 
#     N_ACTION : 6
#     CUBE_RS : 2000.0
#     ACTIONS :
#         - [3.0, 0.4, 0.0, 0.3, 0.0]    # time, pos, gripper
#         - [6.0, 0.4, 0.0, 0.10, 2500.0]
#         - [6.0, 0.4, 0.0, 0.3, 250.0]
#         - [1.0, 0.4, 0.0, 0.3, 250.0]   #pause
#         - [6.0, 0.4, 0.0, 0.10, 250.0]
#         - [6.0, 0.4, 0.0, 0.3, 2000.0]
#     TYPE :                          
#         - [0, 0, 0, 0, 0, 0]     # int, comp
#         - [0, 0, 1, 0, 0, 0]
#         - [0, 0, 1, 0, 0, 1] 
#         - [0, 0, 0, 0, 0, 1]    #pause
#         - [0, 0, 1, 0, 0, 1]
#         - [0, 0, 1, 0, 0, 0]

# PROVA 10: traj più veloce, peso grande, scende,  prende oggetto leggero, sale, riscende, poggia oggetto e torna su 
# traj_par: 
#     N_ACTION : 6
#     CUBE_RS : 2000.0
#     ACTIONS :
#         - [3.0, 0.4, 0.0, 0.3, 0.0]    # time, pos, gripper
#         - [7.0, 0.4, 0.0, 0.10, 3500.0]
#         - [7.0, 0.4, 0.0, 0.3, 400.0]
#         - [1.0, 0.4, 0.0, 0.3, 400.0]   #pause
#         - [7.0, 0.4, 0.0, 0.10, 400.0]
#         - [7.0, 0.4, 0.0, 0.3, 3000.0]
#     TYPE :                          
#         - [0, 0, 0, 0, 0, 0]     # int, comp
#         - [0, 0, 1, 0, 0, 0]
#         - [0, 0, 1, 0, 0, 1] 
#         - [0, 0, 0, 0, 0, 1]    #pause
#         - [0, 0, 1, 0, 0, 1]
#         - [0, 0, 1, 0, 0, 0]        

# PROVA 11: traj più veloce, peso grande, scende,  prende oggetto , sale, vado avanti, poggia oggetto su scatola e torna su 
# F_int_max = 7; F_max = 5; funziona anche con F_int_max =5; F_max = 3;
# traj_par: 
#     N_ACTION : 8
#     CUBE_RS : 2000.0
#     ACTIONS :
#         - [3.0, 0.4, 0.0, 0.4, 0.0]    # time, pos, gripper
#         - [7.0, 0.4, 0.0, 0.10, 3500.0]
#         - [7.0, 0.4, 0.0, 0.4, 400.0]
#         - [1.0, 0.4, 0.0, 0.4, 400.0]   #pause
#         - [7.0, 0.65, 0.0, 0.4, 400]
#         - [7.0, 0.65, 0.0, 0.17, 400.0]
#         - [5.0, 0.65, 0.0, 0.4, 3000.0]
#         - [5.0, 0.4, 0.0, 0.4, 3000.0]
#     TYPE :                          
#         - [0, 0, 0, 0, 0, 0]     # int, comp
#         - [0, 0, 1, 0, 0, 0]
#         - [0, 0, 1, 0, 0, 1] 
#         - [0, 0, 0, 0, 0, 1]    #pause
#         - [0, 0, 0, 0, 0, 1]
#         - [0, 0, 1, 0, 0, 1]
#         - [0, 0, 1, 0, 0, 0]
#         - [0, 0, 0, 0, 0, 0]


# PROVA 12: INTERACTION ON Y: scende giù, va verso sx in +y secondo il frame e-e (NO GRASPING OBJECT), F_int_max = 5; F_max = 3;
# traj_par: 
#     N_ACTION : 3
#     CUBE_RS : 2000.0
#     ACTIONS :
#         - [3.0, 0.4, +0.2, 0.4, 0.0]    # time, pos, gripper
#         - [7.0, 0.4, +0.2, 0.1, 0.0]
#         - [7.0, 0.4, -0.1, 0.1, 0.0]
        
#     TYPE :                          
#         - [0, 0, 0, 0, 0, 0]     # int, comp
#         - [0, 1, 0, 0, 0, 0]
#         - [0, 1, 0, 0, 0, 0] 

# # PROVA 13: GRASPING BOTTIGLIA ACQUA: robot piegato, mi avvicino alla bottiglia, la prendo, mi sollevo su z, mi riavvicino, la ripoggio.
# #F_int_max = 5; F_max = 3
# traj_par: 
#     N_ACTION : 6
#     CUBE_RS : 2000.0
#     ACTIONS :
#         - [5.0, 0.5, 0.0, 0.2, 0.0]    # time, pos, gripper
#         - [10.0, 0.5, -0.2, 0.2, 5000.0]
#         - [10.0, 0.5, -0.2, 0.4, 2700.0]
#         - [3.0, 0.5, -0.2, 0.4, 2700.0]
#         - [10.0, 0.5, -0.2, 0.15,2700.0]
#         - [10.0, 0.5, 0.0, 0.2, 5000.0]

#     TYPE :                          
#         - [0, 0, 0, 0, 0, 0]     # int, comp
#         - [0, 1, 0, 0, 0, 0]
#         - [0, 1, 0, 0, 0, 1] 
#         - [0, 0, 0, 0, 0, 1]     #pause
#         - [0, 0, 1, 0, 0, 1]
#         - [0, 0, 0, 0, 0, 0]

# PROVA 14 : GRASPING+PLACEMENT (CON TRAIETTORIA OBLIQUA) BOTTIGLIA ACQUA CON "MURO": robot piegato, mi avvicino, 
# sollevo la bottiglia, torno indietro (-y), mi riavvicino, la ripoggio, F_int_max = 5; F_max = 3, e_max = 4, Kxy=500, Kz=200
# (altra prova e_max=2 e Kxyz = 300, più bella);
# traj_par: 
#     N_ACTION : 6
#     CUBE_RS : 2000.0
#     ACTIONS :
#         - [5.0, 0.5, 0.0, 0.2, 0.0]    # time, pos, gripper
#         - [10.0, 0.5, -0.23, 0.2, 5000.0]
#         - [5.0, 0.5, -0.23, 0.4, 2700.0]
#         - [7.0, 0.5, 0.0, 0.3, 2700.0]
#         - [10.0, 0.5, -0.2, 0.17,2700.0]
#         - [7.0, 0.5, 0.0, 0.3, 5000.0]

#     TYPE :                          
#         - [0, 0, 0, 0, 0, 0]     # int, comp
#         - [0, 1, 0, 0, 0, 0]
#         - [0, 1, 0, 0, 0, 1] 
#         - [0, 0, 0, 0, 0, 1]     #pause
#         - [0, 1, 1, 0, 0, 1]
#         - [0, 1, 0, 0, 0, 0]

# # PROVA 15 : GRASPING+PLACEMENT INTERAZIONE LUNGO I TRE ASSI, BOTTIGLIA ACQUA CON "MURO AD ANGOLO": robot piegato, mi avvicino, 
# # sollevo la bottiglia, torno indietro (-y), mi riavvicino XY, la ripoggio nell'angolo, F_int_max = 5; F_max = 3, e_max = 2, Kxyz=300;
# traj_par: 
#     N_ACTION : 6
#     CUBE_RS : 2000.0
#     ACTIONS :
#         - [5.0, 0.5, 0.0, 0.2, 0.0]    # time, pos, gripper
#         - [10.0, 0.5, -0.25, 0.2, 5000.0]
#         - [5.0, 0.5, -0.25, 0.4, 2700.0]
#         - [7.0, 0.5, 0.0, 0.4, 2700.0]
#         - [10.0, 0.38, -0.25, 0.17, 2700.0]
#         - [7.0, 0.38, 0.0, 0.3, 5000.0]

#     TYPE :                          
#         - [0, 0, 0, 0, 0, 0]     # int, comp
#         - [0, 1, 0, 0, 0, 0]
#         - [0, 1, 0, 0, 0, 1] 
#         - [0, 1, 0, 0, 0, 1]     #pause
#         - [1, 1, 1, 0, 0, 1]
#         - [1, 1, 1, 0, 0, 0]


# # PROVA 16: RIGIDEZZA TAVOLO: sotto 0.02 fa schifo, vibra, bene 0.01

traj_par: 
    N_ACTION : 7
    CUBE_RS : 2000.0
    ACTIONS :
        - [5.0, 0.51, 0.089, 0.10, 0.0]
        - [7.0, 0.51, 0.089, -0.01, 0.0]
        - [5.0, 0.51, 0.089, 0.10, 0.0]
        - [7.0, 0.51, 0.089, -0.02, 0.0]
        - [5.0, 0.51, 0.089, 0.10, 0.0]
        - [7.0, 0.51, 0.089, -0.03, 0.0]
        - [5.0, 0.51, 0.089, 0.10, 0.0]

    TYPE :                          
        - [0, 0, 0, 0, 0, 0]     # int, comp
        - [0, 0, 1, 0, 0, 0]     #pause
        - [0, 0, 1, 0, 0, 0]
        - [0, 0, 1, 0, 0, 0]
        - [0, 0, 1, 0, 0, 0] 
        - [0, 0, 1, 0, 0, 0]     #pause
        - [0, 0, 1, 0, 0, 0]


# # PROVA 17: POLISHING TASK: bring the spong 

# traj_par: 
#     N_ACTION : 3
#     CUBE_RS : 2000.0
#     ACTIONS :

#         - [5.0, 0.51, 0.089, 0.15, 0.0]
#         - [7.0, 0.51, 0.089, 0.04, 3500.0]
#         - [2.0, 0.51, 0.089, 0.04, 400]


#     TYPE :                          
#         - [0, 0, 0, 0, 0, 0]     # int, comp
#         - [0, 0, 1, 0, 0, 0]
#         - [0, 0, 1, 0, 0, 0] 
